"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: users_api
    version: 1.1.1

    Do not edit the class manually.
"""  # noqa: E501

__all__ = [
    "UserApi",
]
