"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: auth_api
    version: 1.1.1

    Do not edit the class manually.
"""  # noqa: E501

from framework.internal.clients.http.auth_api.apis.auth_api import AuthApi

__all__ = [
    "AuthApi",
]
