"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: {{ service_name|to_snake_case }}
    version: {{ version }}

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field, RootModel


class UserSchema(BaseModel):
    name: Optional[str] = Field(None, description="User real name", title="Name")
    login: Optional[str] = Field(None, description="User real name", title="Login")
    location: Optional[str] = Field(
        None, description="User real location", title="Location"
    )
    icq: Optional[str] = Field(None, description="User ICQ", title="Icq")
    skype: Optional[str] = Field(None, description="User Skype", title="Skype")
    info: Optional[str] = Field(None, description="User info", title="Info")


class UsersSchema(BaseModel):
    users: List[UserSchema] = Field(..., description="List of users", title="Users")


class ValidationErrorLocItem(RootModel[Union[str, int]]):
    root: Union[str, int]


class ValidationError(BaseModel):
    loc: List[ValidationErrorLocItem] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title="Detail")
