"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: register_api
    version: 1.1.1

    Do not edit the class manually.
"""  # noqa: E501

from framework.internal.clients.http.register_api.apis.account_api import AccountApi

__all__ = [
    "AccountApi",
]
